language: java

jdk:
  - openjdk8

dist: trusty

services:
  - docker

before_install:
  - docker pull tarantool/tarantool:2.3

before_script:
  - mvn compile

script:
  - mvn test

notifications:
  email: false

branches:
  only:
    - master