language: java

jdk:
  - openjdk8

dist: trusty

services:
  - docker

before_install:
  - docker pull tarantool/tarantool:2.3

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - mvn verify

notifications:
  email: false

branches:
  only:
    - master